### ISSUE TITLE
Italian translation updates

### ISSUE THREAD

**Issue by goldyfruit** [smartgic/mycroft-sonos-controller-skill#28]
Hi @rbcolom,

Could you please translate these two files from English to Italian?

1. https://github.com/smartgic/mycroft-sonos-controller-skill/blob/21.2.1/vocab/it-it/sonos.which.artist.intent
2. https://github.com/smartgic/mycroft-sonos-controller-skill/blob/21.2.1/dialog/it-it/sonos.nothing.playing.dialog

Thanks :+1:

**Comment by rbcolom** [comment]
#29 #30 done! cheers

**Comment by goldyfruit** [comment]
Thanks @rbcolom!!
